import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "../globals.css";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Next CarMarket test",
  description: "Generated by create next app with Tailwind CSS and shadcn/ui components for a car market test application",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <main className="min-h-screen bg-gray-50">{children}</main>
      </body>
    </html>
  )
}
